import type { Metadata } from "next"
import { DynaPuff, Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

const dynapuff = DynaPuff({
	variable: "--font-dyna-puff",
	subsets: ["latin"],
	weight: ["400", "500", "600"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR">
			<body className={`${dynapuff.variable} antialiased`}>{children}</body>
		</html>
	)
}
